# Generated by Django 5.1.2 on 2024-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.CharField(default='', max_length=500, verbose_name='URL-фото'),
            preserve_default=False,
        ),
    ]
