# Generated by Django 5.1.2 on 2024-11-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_explore'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='image',
            field=models.CharField(default=1, max_length=500, verbose_name='URL-фото'),
            preserve_default=False,
        ),
    ]
