# Generated by Django 5.1.2 on 2024-11-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_explore_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Explore',
            new_name='Trip',
        ),
    ]
