# Generated by Django 5.1.2 on 2024-11-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_explore_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='tour',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
    ]
