# Generated by Django 5.1.2 on 2024-11-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_trip_tour_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='is_featured',
        ),
    ]
