# Generated by Django 5.1.2 on 2024-11-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_exploremore_remove_tour_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_tour', to='myapp.category')),
            ],
        ),
    ]
