# Generated by Django 5.1.2 on 2024-11-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cardtour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtour',
            name='gallery',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Галерея изображений'),
        ),
    ]
