# Generated by Django 5.1.2 on 2024-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cardtour_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
