# Generated by Django 5.1.2 on 2024-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cardtour_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_guests', models.PositiveIntegerField()),
                ('rooms_count', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=500, verbose_name='URL-фото')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
