# Generated by Django 5.1.2 on 2024-11-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hotel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
    ]
