# Generated by Django 5.1.2 on 2024-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_hotel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
