# Generated by Django 5.1.2 on 2024-11-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_hotelimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
