# Generated by Django 5.1.2 on 2024-11-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_image_url_hotelimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelimage',
            old_name='image',
            new_name='image_url',
        ),
    ]
