# Generated by Django 5.1.2 on 2024-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_image_hotelimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='gallery',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Галерея изображений'),
        ),
    ]
