# Generated by Django 5.1.2 on 2024-11-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_hotelimage_image_url_hotelimage_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelimage',
            name='image',
            field=models.CharField(default=1, max_length=500, verbose_name='URL-фото'),
            preserve_default=False,
        ),
    ]
