# Generated by Django 5.1.2 on 2024-11-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelimage',
            name='image',
        ),
    ]
