# Generated by Django 5.1.2 on 2024-11-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_hotelimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtour',
            name='image',
        ),
    ]
