# Generated by Django 5.1.2 on 2024-11-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_cardtour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtour',
            name='image',
            field=models.CharField(default=1, max_length=500, verbose_name='URL-фото'),
            preserve_default=False,
        ),
    ]
