# Generated by Django 5.1.2 on 2024-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_tour_end_date_tour_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(default='2024-02-01'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
