# Generated by Django 5.1.2 on 2024-11-17 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_userselection_number_of_people_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='tour',
        ),
        migrations.AddField(
            model_name='userselection',
            name='card_tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.cardtour'),
        ),
    ]
