# Generated by Django 5.1.2 on 2024-11-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_userselection_card_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userselection',
            name='card_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cardtour'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hotel'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
