# Generated by Django 5.1.2 on 2024-11-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_userselection_number_of_people_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
