# Generated by Django 5.1.2 on 2024-11-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_delete_userselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='explore_more_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.exploremore'),
        ),
    ]
