# Generated by Django 5.1.2 on 2024-11-19 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_tour_explore_more_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='explore_more_section',
        ),
    ]
